spring:
  application:
    name: thanh toan service
  datasource:
    url: jdbc:mysql://localhost:3306/datvexe
    username: root
    password: 12345
  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
