server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: quan-ly-service
          uri: http://localhost:8082
          predicates:
            - Path=/quanly/**
          filters:
            - AuthenticationFilter

        - id: thanh-toan-service
          uri: http://localhost:8083
          predicates:
            - Path=/thanhtoan/**

        - id: dat-ve-service
          uri: http://localhost:8084
          predicates:
            - Path=/datve/**

