server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://DiscoveryServer:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: login-service
          uri: http://login-service:8081
          predicates:
            - Path=/auth/**

        - id: quan-ly-service
          uri: http://quanly-service:8082
          predicates:
            - Path=/manage/**
          filters:
            - AuthenticationFilter

        - id: thanh-toan-service
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/thanhtoan/**

        - id: dat-ve-service
          uri: http://datve-service:8084
          predicates:
            - Path=/datve/**, /chuyenxe/**, /nvquanly/**, /vexe/**
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#      routes:
#        - id: login-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/auth/**
#
#        - id: quan-ly-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/manage/**
#          filters:
#            - AuthenticationFilter
#
#        - id: thanh-toan-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/thanhtoan/**
#
#        - id: dat-ve-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/datve/**, /chuyenxe/**, /nvquanly/**, /vexe/**