server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: login-service
            uri: http://localhost:8081
            predicates:
            - Path=/**
          - id: quan-ly-service
            uri: http://localhost:8082
            predicates:
              - Path=/quanly/**


