spring:
  application:
    name: login service
  datasource:
    url: jdbc:mysql://localhost:3306/datvexe
    username: root
    password:
#    password: 270701
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/








